version: '3'

networks:
  app-network:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network
    volumes:
      - ./redis.conf:/opt/bitnami/redis/mounted-etc/redis.conf