version: "3.9"

services:
  redis:
    container_name: redis
    image: "bitnami/redis:latest"
    user: "root"
    environment:
      REDIS_PORT: 6379
      REDIS_PASSWORD: redis
    ports:
      - 6379:6379
    restart: always
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local